import {beforeAll,afterAll,beforeEach,afterEach,describe,it,expect} from 'vitest';
import pg from 'pg';
// Nunca usa .env.local implicitamente: integração só com URL fornecida explicitamente.
const url=process.env.SUPABASE_DB_URL;
describe.skipIf(!url)('central operacional: calendário, filas, despacho e RLS',()=>{
 let db:pg.Client;let org:string,canal:string,contato:string,conversa:string,regra:string,usuario:string,membro:string,equipe:string;
 const q=async(sql:string,args:unknown[]=[]) => (await db.query(sql,args)).rows;
 beforeAll(async()=>{db=new pg.Client({connectionString:url,ssl:url?.includes('localhost')?false:{rejectUnauthorized:false}});await db.connect();});
 afterAll(async()=>{await db?.end();});
 beforeEach(async()=>{
 await q('begin');await q("select set_config('request.jwt.claims','{\"role\":\"service_role\"}',true)");org=(await q("insert into organizacoes(nome,apelido) values('Teste operacional',gen_random_uuid()::text) returning id"))[0].id;
 usuario=(await q("insert into auth.users(email) values('operacao@teste.local') returning id"))[0].id;
 membro=(await q("insert into membros_organizacao(organizacao_id,perfil_id,papel) values($1,$2,'ATENDENTE') returning id",[org,usuario]))[0].id;
 equipe=(await q("insert into departamentos(organizacao_id,nome,chave) values($1,'Comercial','comercial') returning id",[org]))[0].id;
 await q('insert into membros_departamento(organizacao_id,membro_id,departamento_id) values($1,$2,$3)',[org,membro,equipe]);
 canal=(await q("insert into canais(organizacao_id,nome,provedor,status,departamento_id,identificador_externo) values($1,'Simulado','SIMULADO','CONECTADO',$2,gen_random_uuid()::text) returning id",[org,equipe]))[0].id;
 contato=(await q("insert into contatos(organizacao_id,nome,telefone,departamento_id,responsavel_id) values($1,'Cliente','5511999990000',$2,$3) returning id",[org,equipe,membro]))[0].id;
 regra=(await q("insert into regras_atendimento(organizacao_id,versao) values($1,1) returning id",[org]))[0].id;
 conversa=(await q("insert into conversas(organizacao_id,contato_id,canal_id,departamento_id,estado) values($1,$2,$3,$4,'AGUARDANDO_HUMANO') returning id",[org,contato,canal,equipe]))[0].id;
 });afterEach(async()=>{await q('rollback');});
 async function entrada(data='2026-09-18T20:58:00Z'){return (await q("insert into mensagens(organizacao_id,conversa_id,contato_id,canal_id,direcao,autor,tipo,conteudo,status,criado_em) values($1,$2,$3,$4,'ENTRADA','CONTATO','TEXTO','Preciso de ajuda','ENTREGUE',$5) returning id",[org,conversa,contato,canal,data]))[0].id;}
 async function saida(autor='IA'){return (await q("insert into mensagens(organizacao_id,conversa_id,contato_id,canal_id,direcao,autor,autor_membro_id,tipo,conteudo,status) values($1,$2,$3,$4,'SAIDA',$5,$6,'TEXTO','Resposta','PENDENTE') returning id",[org,conversa,contato,canal,autor,autor==='ATENDENTE'?membro:null]))[0].id;}
 async function autenticar(){await q("select set_config('request.jwt.claims',$1,true)",[JSON.stringify({sub:usuario,role:'authenticated'})]);await q('set local role authenticated');}
 it('17h58 de sexta + 10 minutos úteis vence segunda 09h08',async()=>{const r=await q("select prazo_util('2026-09-18T20:58:00Z',10,$1) prazo",[regra]);expect(r[0].prazo.toISOString()).toBe('2026-09-21T12:08:00.000Z');});
 it('feriado não consome o prazo',async()=>{await q("update regras_atendimento set feriados='{2026-09-21}' where id=$1",[regra]);const r=await q("select prazo_util('2026-09-18T20:58:00Z',10,$1) prazo",[regra]);expect(r[0].prazo.toISOString()).toBe('2026-09-22T12:08:00.000Z');});
 it('jornada noturna atravessa meia-noite',async()=>{await q(`update regras_atendimento set intervalos='[{"inicio":"22:00","fim":"06:00"}]' where id=$1`,[regra]);const r=await q("select prazo_util('2026-09-19T02:58:00Z',10,$1) prazo",[regra]);expect(r[0].prazo.toISOString()).toBe('2026-09-19T03:08:00.000Z');});
 it('sugestão de retorno considera dias úteis',async()=>{const r=await q("select prazo_retorno_util('2026-09-18T16:00:00Z',$1) prazo",[regra]);expect(r[0].prazo.toISOString()).toBe('2026-09-22T16:00:00.000Z');});
 it('nova mensagem não reinicia a espera existente',async()=>{await entrada();await entrada('2026-09-18T21:00:00Z');const e=await q('select * from esperas_humanas where conversa_id=$1',[conversa]);expect(e).toHaveLength(1);expect(e[0].inicio.toISOString()).toBe('2026-09-18T20:58:00.000Z');});
 it('assumir não conta como primeira resposta humana',async()=>{await entrada();await q('select assumir_conversa($1,$2)',[conversa,membro]);const c=(await q('select * from conversas where id=$1',[conversa]))[0];expect(c.primeira_resposta_humana_em).toBeNull();expect((await q('select respondida_em from esperas_humanas where conversa_id=$1',[conversa]))[0].respondida_em).toBeNull();});
 it('resposta só fecha espera quando aceita; falha a reabre',async()=>{await entrada();await q('select assumir_conversa($1,$2)',[conversa,membro]);const id=await saida('ATENDENTE');expect((await q('select respondida_em from esperas_humanas where conversa_id=$1',[conversa]))[0].respondida_em).toBeNull();await q("update mensagens set status='ENVIADA',enviado_em='2026-09-21T12:08:00Z' where id=$1",[id]);expect(Number((await q('select segundos_uteis from esperas_humanas where conversa_id=$1',[conversa]))[0].segundos_uteis)).toBe(600);await q("update mensagens set status='FALHOU' where id=$1",[id]);expect((await q('select respondida_em from esperas_humanas where conversa_id=$1',[conversa]))[0].respondida_em).toBeNull();});
 it('mudança de regra preserva a meta da espera aberta',async()=>{await entrada();await q('insert into regras_atendimento(organizacao_id,versao,meta_minutos) values($1,2,30)',[org]);expect((await q('select regra_id from esperas_humanas where conversa_id=$1',[conversa]))[0].regra_id).toBe(regra);});
 it('resposta da IA já enfileirada é cancelada ao assumir',async()=>{await q("update conversas set estado='IA' where id=$1",[conversa]);const id=await saida();await q('select assumir_conversa($1,$2)',[conversa,membro]);expect(await q('select * from reservar_despacho_mensagem($1,$2)',[id,org])).toHaveLength(0);expect((await q('select status from mensagens where id=$1',[id]))[0].status).toBe('FALHOU');});
 it('a última checagem do envio reconhece tomada de posse após reserva',async()=>{await q("update conversas set estado='IA' where id=$1",[conversa]);const id=await saida();await q('select * from reservar_despacho_mensagem($1,$2)',[id,org]);await q('select assumir_conversa($1,$2)',[conversa,membro]);expect((await q('select iniciar_despacho($1,$2) ok',[id,org]))[0].ok).toBe(false);});
 it('envio externo em andamento bloqueia mudança de atendimento',async()=>{await q("update conversas set estado='IA' where id=$1",[conversa]);const id=await saida();await q('select * from reservar_despacho_mensagem($1,$2)',[id,org]);expect((await q('select iniciar_despacho($1,$2) ok',[id,org]))[0].ok).toBe(true);await expect(q('select assumir_conversa($1,$2)',[conversa,membro])).rejects.toThrow('envio em confirmação');});
 it('reserva expirada não repete chamada externa de resultado desconhecido',async()=>{await q("update conversas set estado='IA' where id=$1",[conversa]);const id=await saida();await q('select * from reservar_despacho_mensagem($1,$2)',[id,org]);await q('select iniciar_despacho($1,$2)',[id,org]);await q("update mensagens set despacho_reservado_ate=now()-interval '1 hour' where id=$1",[id]);expect(await q('select * from reservar_despacho_mensagem($1,$2)',[id,org])).toHaveLength(0);});
 it('entrada com estado antigo não devolve conversa humana para IA',async()=>{await q('select assumir_conversa($1,$2)',[conversa,membro]);expect((await q("select atualizar_conversa_recebida($1,$2,'Nova mensagem',now()) estado",[conversa,org]))[0].estado).toBe('HUMANO');});
 it('RLS restringe conversa, contato e nota de outra equipe',async()=>{await q("update contatos set departamento_id=null,responsavel_id=null where id=$1",[contato]);const e=(await q("insert into departamentos(organizacao_id,nome,chave) values($1,'Privado','privado') returning id",[org]))[0].id;await q('update conversas set departamento_id=$2 where id=$1',[conversa,e]);await q('update contatos set departamento_id=$2 where id=$1',[contato,e]);await q("insert into notas_internas(organizacao_id,conversa_id,conteudo) values($1,$2,'Privado')",[org,conversa]);await autenticar();expect(await q('select id from conversas where id=$1',[conversa])).toHaveLength(0);expect(await q('select id from contatos where id=$1',[contato])).toHaveLength(0);expect(await q('select id from notas_internas where conversa_id=$1',[conversa])).toHaveLength(0);});
 it('atendente não pode alterar diretamente o estado da conversa',async()=>{await autenticar();await expect(q("update conversas set estado='IA' where id=$1",[conversa])).rejects.toThrow('permission denied');});
 it('escopo próprias limita conversas mesmo na equipe',async()=>{await q("update membros_organizacao set escopo_conversas='PROPRIAS' where id=$1",[membro]);await autenticar();expect(await q('select id from conversas where id=$1',[conversa])).toHaveLength(0);});
 it('receber durante despacho da IA preserva a mensagem sem permitir troca de dono',async()=>{await q("update conversas set estado='AGUARDANDO_CLIENTE' where id=$1",[conversa]);const id=await saida();await q('select * from reservar_despacho_mensagem($1,$2)',[id,org]);await q('select iniciar_despacho($1,$2)',[id,org]);expect((await q("select atualizar_conversa_recebida($1,$2,'Nova pergunta',now()) estado",[conversa,org]))[0].estado).toBe('IA');expect((await q('select nao_lidas from conversas where id=$1',[conversa]))[0].nao_lidas).toBe(1);await expect(q('select assumir_conversa($1,$2)',[conversa,membro])).rejects.toThrow('envio em confirmação');});
 it('fila usa envio efetivo e não criação tardia ao reconhecer resposta do cliente',async()=>{await q('select assumir_conversa($1,$2)',[conversa,membro]);const id=await saida('ATENDENTE');await q("update mensagens set status='ENVIADA',enviado_em='2026-09-18T18:00:00Z' where id=$1",[id]);await entrada('2026-09-18T19:00:00Z');const f=(await q('select * from fila_operacional where id=$1',[conversa]))[0];expect(f.ultimo_autor).toBe('CONTATO');expect(f.para_responder).toBe(true);expect(f.aguardando_cliente).toBe(false);expect(f.sugestao_retorno).toBe(false);});
 it('nota e leitura não encerram pendência humana',async()=>{await entrada();await q('select assumir_conversa($1,$2)',[conversa,membro]);await q('update conversas set nao_lidas=0 where id=$1',[conversa]);await q("insert into notas_internas(organizacao_id,conversa_id,autor_membro_id,conteudo) values($1,$2,$3,'Nota interna')",[org,conversa,membro]);const f=(await q('select * from fila_operacional where id=$1',[conversa]))[0];expect(f.para_responder).toBe(true);expect(f.ultimo_autor).toBe('CONTATO');});
 it('atendente não consegue forjar autoria de nota interna',async()=>{await autenticar();await expect(q("insert into notas_internas(organizacao_id,conversa_id,conteudo) values($1,$2,'Nota sem autor')",[org,conversa])).rejects.toThrow('row-level security');});
 it('retorno exige responsável com acesso à equipe',async()=>{const outroUsuario=(await q("insert into auth.users(email) values('outra-equipe@teste.local') returning id"))[0].id;const outro=(await q("insert into membros_organizacao(organizacao_id,perfil_id,papel) values($1,$2,'ATENDENTE') returning id",[org,outroUsuario]))[0].id;await expect(q("insert into retornos(organizacao_id,conversa_id,responsavel_id,criado_por,motivo,prazo) values($1,$2,$3,$4,'Retomar',now())",[org,conversa,outro,membro])).rejects.toThrow('Responsável sem acesso');});
 it('retorno tem versão otimista e não envia mensagem ao reagendar',async()=>{const id=(await q("insert into retornos(organizacao_id,conversa_id,responsavel_id,criado_por,motivo,prazo) values($1,$2,$3,$3,'Retomar',now()) returning id",[org,conversa,membro]))[0].id;await autenticar();expect(await q("update retornos set prazo=now()+interval '1 day' where id=$1 and versao=1 returning id",[id])).toHaveLength(1);expect(await q("update retornos set prazo=now()+interval '2 days' where id=$1 and versao=1 returning id",[id])).toHaveLength(0);expect(await q('select id from mensagens where conversa_id=$1',[conversa])).toHaveLength(0);expect((await q('select versao from retornos where id=$1',[id]))[0].versao).toBe(2);});
 it('primeira resposta humana é registrada somente na aceitação e removida se falhar',async()=>{await entrada();await q('select assumir_conversa($1,$2)',[conversa,membro]);const id=await saida('ATENDENTE');await q("update mensagens set status='ENVIADA',enviado_em='2026-09-21T12:08:00Z' where id=$1",[id]);expect((await q('select primeira_resposta_humana_em t from conversas where id=$1',[conversa]))[0].t.toISOString()).toBe('2026-09-21T12:08:00.000Z');await q("update mensagens set status='FALHOU' where id=$1",[id]);expect((await q('select primeira_resposta_humana_em t from conversas where id=$1',[conversa]))[0].t).toBeNull();});

 it('conclusão recusa a versão anterior a uma nova entrada',async()=>{await q('select assumir_conversa($1,$2)',[conversa,membro]);const v=(await q('select versao from conversas where id=$1',[conversa]))[0].versao;await entrada();expect((await q('select encerrar_conversa_com_versao($1,$2,$3) ok',[conversa,membro,v]))[0].ok).toBe(false);expect((await q('select estado from conversas where id=$1',[conversa]))[0].estado).toBe('HUMANO');});
 it('entrada associada durante conclusão reabre sem perder responsável',async()=>{await q('select assumir_conversa($1,$2)',[conversa,membro]);const v=(await q('select versao from conversas where id=$1',[conversa]))[0].versao;expect((await q('select encerrar_conversa_com_versao($1,$2,$3) ok',[conversa,membro,v]))[0].ok).toBe(true);await entrada(new Date(Date.now()+1000).toISOString());const c=(await q('select estado,responsavel_id,encerrada_em from conversas where id=$1',[conversa]))[0];expect(c.estado).toBe('HUMANO');expect(c.responsavel_id).toBe(membro);expect(c.encerrada_em).toBeNull();expect(await q("select id from eventos_conversa where conversa_id=$1 and tipo='REABERTA'",[conversa])).toHaveLength(1);});
});
