'use client';
import { useState } from 'react';
import { CalendarPlus,Info } from 'lucide-react';
import { toast } from 'sonner';
import { useRouter } from 'next/navigation';
import { Dialogo,ConteudoDialogo,CorpoDialogo,RodapeDialogo } from '@/componentes/ui/dialogo';
import { Botao } from '@/componentes/ui/botao';
import { salvarRetorno } from '@/lib/operacao/acoes';
import { dataLocal } from '@/lib/operacao/calendario';
import type { Retorno } from '@/lib/operacao/tipos';
export function AgendarRetorno({conversaId,nome,membroId,fuso,retorno,atendentes=[]}:{conversaId:string;nome:string;membroId:string;fuso:string;retorno?:Retorno;atendentes?:{membroId:string;nome:string}[]}){
 const [aberto,setAberto]=useState(false),[ocupado,setOcupado]=useState(false);const router=useRouter();
 const [id,setId]=useState(''),[erro,setErro]=useState('');
 async function salvar(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setOcupado(true);setErro('');try{const r=await salvarRetorno({id,conversaId,responsavelId:String(f.get('responsavel')),motivo:String(f.get('motivo')),prazo:String(f.get('prazo')),permitirPassado:f.get('passado')==='on',versao:retorno?.versao});if(!r.ok){setErro(r.erro||'Não foi possível salvar.');return;}toast.success(retorno?'Retorno reagendado.':'Retorno agendado.');setAberto(false);router.refresh();}catch{setErro('Falha de conexão. Seu formulário foi preservado.');}finally{setOcupado(false);}}
 return <><button className="botao-link w-full" onClick={()=>{setId(retorno?.id||crypto.randomUUID());setAberto(true);}}><CalendarPlus size={15}/>{retorno?'Reagendar':'Agendar retorno'}</button><Dialogo open={aberto} onOpenChange={setAberto}><ConteudoDialogo titulo={retorno?'Reagendar retorno':'Agendar retorno'} descricao={nome}><form onSubmit={salvar}><CorpoDialogo><div className="space-y-4"><label className="block text-xs">Próxima ação<input name="motivo" required maxLength={500} defaultValue={retorno?.motivo} className="campo-operacional mt-1" placeholder="Ex.: confirmar análise da proposta"/></label><label className="block text-xs">Prazo · {fuso}<input type="datetime-local" name="prazo" required defaultValue={retorno?dataLocal(retorno.prazo,fuso):''} className="campo-operacional mt-1"/></label><label className="block text-xs">Responsável<select name="responsavel" defaultValue={retorno?.responsavel_id||membroId} className="campo-operacional mt-1">{retorno&&retorno.responsavel_id!==membroId&&!atendentes.some(a=>a.membroId===retorno.responsavel_id)&&<option value={retorno.responsavel_id}>Responsável atual</option>}{atendentes.length?atendentes.map(a=><option key={a.membroId} value={a.membroId}>{a.nome}</option>):<option value={membroId}>Eu</option>}</select></label><label className="flex items-center gap-2 text-xs"><input name="passado" type="checkbox"/>Permitir cadastrar um prazo já vencido</label><p className="flex gap-2 rounded bg-bruma-50 p-3 text-xs text-bruma-600"><Info size={16} className="shrink-0"/>Agendar cria uma tarefa. Nenhuma mensagem será enviada automaticamente.</p>{erro&&<p role="alert" className="text-sm text-marca-600">{erro}</p>}</div></CorpoDialogo><RodapeDialogo><Botao type="button" variante="secundario" onClick={()=>setAberto(false)}>Cancelar</Botao><Botao type="submit" carregando={ocupado}>Salvar retorno</Botao></RodapeDialogo></form></ConteudoDialogo></Dialogo></>;
}
