import Link from 'next/link';
import { MonitorIa } from './monitor-ia';
import { Sparkles,TriangleAlert,ArrowRight,Info } from 'lucide-react';
import { exigirPapel } from '@/lib/sessao';
import { clienteServidor } from '@/lib/supabase/servidor';
import { carregarFila,lerFiltros } from '@/lib/operacao/dados';
import { carregarApoio,carregarDetalheConversa } from '@/app/(painel)/atendimento/dados';
import { CabecalhoPagina,Selo } from '@/componentes/ui/estrutura';
import { FiltrosEquipe } from './filtros';
import { FilaTabela,Identidade,Metricas } from './compartilhados';
import { Intervencao } from './intervencao';
import { SincronizadorLista } from '@/app/(painel)/atendimento/sincronizador';
import { formatarHora } from '@/lib/utilitarios';
type Carga={id:string|null;nome:string;abertas:number;responder:number;vencidos:number};
export async function GestaoOperacional({parametros,modo}:{parametros:Record<string,string|string[]|undefined>;modo:'supervisao'|'equipes'|'ia'}){
 const s=await exigirPapel('SUPERVISOR');const db=await clienteServidor();const filtros=lerFiltros(parametros);
 const aba=typeof parametros.aba==='string'?parametros.aba:'apoio';
 if(modo==='equipes')filtros.caixa='todos';if(modo==='ia')filtros.caixa=aba==='ativas'?'ia':aba==='falhas'?'falhas-ia':'apoio';
 const [fila,apoio,carga,canais]=await Promise.all([carregarFila(filtros),carregarApoio(s.organizacao.id),db.rpc('carga_consultores',{p_equipe:filtros.equipe||null,p_canal:filtros.canal||null}),db.from('canais').select('id,nome').eq('organizacao_id',s.organizacao.id).order('nome')]);
 if(carga.error)throw new Error('Não foi possível carregar a distribuição da equipe.');
 const cargas=carga.data as unknown as Carga[];
 const itens=fila.itens;
 const pedido=typeof parametros.conversa==='string'?parametros.conversa:null;
 const escolhido=itens.find(i=>i.id===pedido)||itens[0];const detalhe=escolhido?await carregarDetalheConversa(s.organizacao.id,escolhido.id):null;
 const titulo=modo==='supervisao'?'Supervisão da operação':modo==='equipes'?'Equipes':'Assistente IA';
 const caminho=modo==='ia'?'/assistente-ia':'/'+modo;
 function link(m:Record<string,string>){const q=new URLSearchParams();for(const [k,v]of Object.entries(parametros)){if(typeof v==='string')q.set(k,v);}for(const [k,v]of Object.entries(m))v?q.set(k,v):q.delete(k);return caminho+'?'+q;}
 if(['ia'].includes(modo))return <MonitorIa itens={itens} contagens={fila.contagens} detalhe={detalhe} escolhido={escolhido} apoio={apoio} aba={aba} link={link} fuso={s.organizacao.fuso_horario} organizacaoId={s.organizacao.id} pagina={fila.pagina} total={fila.total} canais={canais.data||[]}/>;
 return <div className="pagina-operacional"><CabecalhoPagina titulo={titulo} descricao={modo==='supervisao'?'Acompanhe as filas e distribua os atendimentos.':modo==='equipes'?'Distribua a demanda com contexto.':'Acompanhe e intervenha quando necessário.'} acoes={modo==='equipes'&&s.papel!=='SUPERVISOR'?<Link className="botao-link" href="/configuracoes/departamentos">Gerenciar equipe</Link>:undefined}/>{modo==='ia'&&<nav className="abas-operacionais mb-4"><Link href="/assistente-ia" aria-current="page">Monitoramento</Link><Link href="/ia">Configuração</Link></nav>}<div className="mb-4 flex justify-end"><FiltrosEquipe apoio={apoio} canais={canais.data||[]} atualizado={formatarHora(new Date(),s.organizacao.fuso_horario)}/></div><Metricas contagens={fila.contagens} filtros={filtros}/>{(fila.contagens['sem-responsavel']||0)>0&&<div className="aviso-operacional my-3"><TriangleAlert size={18}/>{fila.contagens['sem-responsavel']} conversas aguardam atribuição<Link href="/atendimento?caixa=sem-responsavel&escopo=equipe" className="ml-auto underline">Distribuir agora →</Link></div>}{modo==='ia'&&<nav className="abas-operacionais my-3">{([['apoio','Pedindo apoio'],['ativas','Em atendimento'],['falhas','Falhas']] as const).map(([v,n])=><Link key={v} href={link({aba:v,pagina:''})} aria-current={aba===v?'page':undefined}>{n}</Link>)}</nav>}
 <div className="painel-dividido mt-3"><div className="min-w-0 space-y-3">{modo==='equipes'&&<CargaTabela cargas={cargas} link={link}/>}<section className="superficie"><h2 className="titulo-painel">{modo==='supervisao'?'Fila que precisa de atenção':modo==='ia'?'Fila de atendimentos':filtros.responsavel?'Fila do consultor':'Fila da equipe'}</h2>{modo==='ia'?<ul className="divide-y">{itens.map(i=><li key={i.id}><Link href={link({conversa:i.id})} className={'flex items-center gap-3 rounded p-3 '+(escolhido?.id===i.id?'bg-produto-50':'')}><Identidade nome={i.contato_nome} pequeno/><span className="ml-auto text-xs text-bruma-600">{i.falhas_envio?i.falhas_envio+' falhas':i.estado==='AGUARDANDO_HUMANO'?'Precisa de um humano':'Com IA'}</span></Link></li>)}{!itens.length&&<p className="p-8 text-center text-sm text-bruma-600">Nenhum atendimento neste filtro.</p>}</ul>:<><FilaTabela itens={itens} acao="Selecionar" destino={id=>link({conversa:id})}/></>}{fila.total>40&&<div className="mt-3 flex justify-end gap-3 text-xs">{fila.pagina>1&&<Link href={link({pagina:String(fila.pagina-1)})}>← Anterior</Link>}{fila.pagina*40<fila.total&&<Link href={link({pagina:String(fila.pagina+1)})}>Próxima →</Link>}</div>}</section>{modo==='supervisao'&&<CargaTabela cargas={cargas} link={link}/>}</div><aside className="superficie">{escolhido&&detalhe?<><div className="mb-4 flex items-center justify-between"><h2 className="titulo-painel !mb-0">{modo==='equipes'?'Distribuir atendimento':modo==='ia'?'Conversa em análise':'Atendimento em foco'}</h2>{escolhido.com_ia&&<Selo tom="ia"><Sparkles size={12}/>IA ativa</Selo>}</div><Identidade nome={escolhido.contato_nome} telefone={escolhido.canal_nome}/>{modo!=='equipes'&&<div className="my-4 space-y-3 border-y py-4">{detalhe.mensagens.filter(m=>m.tipo!=='SISTEMA').slice(-3).map(m=><div key={m.id} className={m.autor==='IA'?'rounded bg-ia-50 p-2.5 text-ia-700':'rounded bg-bruma-100 p-2.5'}><span className="mb-1 block text-[10px] text-bruma-600">{m.autor==='CONTATO'?escolhido.contato_nome:m.remetente_nome||m.autor} · {formatarHora(m.criado_em,s.organizacao.fuso_horario)}</span><p className="whitespace-pre-wrap text-xs leading-relaxed">{m.conteudo||'Mensagem de mídia'}</p></div>)}</div>}<Intervencao key={escolhido.id} item={escolhido} apoio={apoio} transferenciaInicial={modo==='equipes'}/><Link href={'/atendimento?conversa='+escolhido.id} className="mt-4 flex items-center justify-center gap-2 text-xs text-produto-800">Abrir conversa completa<ArrowRight size={14}/></Link><p className="mt-4 flex gap-2 border-t pt-3 text-[11px] text-bruma-600"><Info size={15} className="shrink-0"/>A IA só retoma após uma ação explícita.</p></>:<p className="py-10 text-center text-sm text-bruma-600">Selecione um atendimento para ver o contexto e intervir.</p>}</aside></div><SincronizadorLista organizacaoId={s.organizacao.id}/></div>;
}
function CargaTabela({cargas,link}:{cargas:Carga[];link:(m:Record<string,string>)=>string}){return <section className="superficie"><h2 className="titulo-painel">Carga por consultor</h2><p className="mb-3 text-xs text-bruma-600">Contagens atuais; sem estimativa de capacidade.</p><div className="tabela-container"><table className="tabela-operacional"><thead><tr><th>Consultor</th><th>Abertas</th><th>Para responder</th><th>Vencidos</th><th>Ação</th></tr></thead><tbody>{cargas.map(c=><tr key={c.id||'sem'}><td><Identidade nome={c.nome} pequeno/></td><td>{c.abertas}</td><td>{c.responder}</td><td>{c.vencidos}</td><td><Link className="botao-link" href={c.id?link({responsavel:c.id,pagina:''}):'/atendimento?caixa=sem-responsavel&escopo=equipe'}>Ver fila</Link></td></tr>)}</tbody></table>{!cargas.length&&<p className="p-5 text-center text-xs text-bruma-600">Nenhuma conversa aberta.</p>}</div></section>;}
