'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { ArrowRightLeft,Hand,Info,X } from 'lucide-react';
import { assumirConversa,transferirConversa } from '@/app/(painel)/atendimento/acoes';
import type { ApoioAtendimento } from '@/app/(painel)/atendimento/tipos';
import type { FilaOperacional } from '@/lib/operacao/tipos';
import { Identidade } from './compartilhados';
import { Botao } from '@/componentes/ui/botao';
export function Intervencao({item,apoio,transferenciaInicial=false}:{item:FilaOperacional;apoio:ApoioAtendimento;transferenciaInicial?:boolean}){
 const [transferindo,setTransferindo]=useState(transferenciaInicial),[ocupado,setOcupado]=useState(false),[erro,setErro]=useState('');const router=useRouter();
 async function assumir(){setOcupado(true);try{const r=await assumirConversa(item.id);if(!r.ok)setErro(r.erro||'Não foi possível assumir.');else router.push('/atendimento?conversa='+item.id);}catch{setErro('Falha de conexão. Atualize antes de tentar novamente.');}finally{setOcupado(false);}}
 async function transferir(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setOcupado(true);setErro('');try{const r=await transferirConversa({conversaId:item.id,departamentoId:String(f.get('equipe')||'')||null,membroId:String(f.get('membro')||'')||null,motivo:String(f.get('motivo')||''),nota:String(f.get('nota')||'')});if(!r.ok){setErro(r.erro||'Não foi possível transferir.');return;}setTransferindo(false);router.refresh();}catch{setErro('Falha de conexão. Confira o responsável atual antes de repetir.');}finally{setOcupado(false);}}
 return <div className="space-y-3">{erro&&<p role="alert" className="rounded bg-marca-50 p-3 text-xs text-marca-600">{erro}</p>}{transferindo?<form onSubmit={transferir} className="space-y-4"><div className="flex items-center justify-between"><h3 className="titulo-painel !mb-0">Transferir atendimento</h3><button type="button" aria-label="Fechar transferência" onClick={()=>setTransferindo(false)}><X size={16}/></button></div><Identidade nome={item.contato_nome} telefone={item.canal_nome} foto={item.contato_foto}/><p className="text-xs text-bruma-600">De: {item.responsavel_nome||'Sem responsável'} · {item.equipe_nome||'Sem equipe'}</p><label className="block text-xs">Equipe de destino<select required name="equipe" className="campo-operacional mt-1" defaultValue={item.departamento_id||''}><option value="">Selecione a equipe</option>{apoio.departamentos.map(d=><option key={d.id} value={d.id}>{d.nome}</option>)}</select></label><label className="block text-xs">Consultor<select name="membro" className="campo-operacional mt-1" defaultValue=""><option value="">Fila da equipe · sem responsável</option>{apoio.atendentes.map(a=><option key={a.membroId} value={a.membroId}>{a.nome}</option>)}</select></label><label className="block text-xs">Motivo<input name="motivo" required maxLength={500} className="campo-operacional mt-1" placeholder="Ex.: redistribuição de demanda"/></label><label className="block text-xs">Nota interna<textarea name="nota" rows={3} maxLength={2000} className="mt-1 w-full rounded border p-2" placeholder="Contexto para quem vai continuar"/></label><p className="flex items-center gap-2 text-xs text-bruma-600"><Info size={15}/>A transferência mantém o histórico e a espera.</p><Botao type="submit" className="w-full" carregando={ocupado}>Confirmar transferência</Botao></form>:<><Botao className="w-full" carregando={ocupado} onClick={()=>void assumir()}><Hand size={16}/>Assumir e pausar IA</Botao><button className="botao-link w-full" onClick={()=>setTransferindo(true)}><ArrowRightLeft size={15}/>Transferir para equipe</button></>}</div>;
}
