import Link from 'next/link';
import { Bot, Clock3, Info, Sparkles, TriangleAlert } from 'lucide-react';
import type { ApoioAtendimento, DetalheConversa } from '@/app/(painel)/atendimento/tipos';
import { SincronizadorLista } from '@/app/(painel)/atendimento/sincronizador';
import type { FilaOperacional } from '@/lib/operacao/tipos';
import { formatarEspera, formatarHora } from '@/lib/utilitarios';
import { CabecalhoPagina } from '@/componentes/ui/estrutura';
import { FiltrosEquipe } from './filtros';
import { Identidade } from './compartilhados';
import { Intervencao } from './intervencao';

export function MonitorIa({ itens, contagens, detalhe, escolhido, apoio, aba, link, fuso, organizacaoId, pagina, total, canais }: {
  itens:FilaOperacional[];contagens:Record<string,number>;detalhe:DetalheConversa|null;escolhido?:FilaOperacional;
  apoio:ApoioAtendimento;aba:string;link:(p:Record<string,string>)=>string;fuso:string;organizacaoId:string;pagina:number;total:number;canais:{id:string;nome:string}[];
}) {
  const cards=[{aba:'ativas',chave:'ia',nome:'Em atendimento',Icone:Bot,cor:'text-produto-800 bg-produto-50'}, {aba:'apoio',chave:'apoio',nome:'Pedindo apoio',Icone:Clock3,cor:'text-alerta-700 bg-alerta-100'}, {aba:'falhas',chave:'falhas-ia',nome:'Falhas',Icone:TriangleAlert,cor:'text-marca-600 bg-marca-50'}];
  return <div className="pagina-operacional">
    <CabecalhoPagina titulo="Assistente IA" descricao="Acompanhe e intervenha quando necessário."/>
    <nav className="abas-operacionais mb-3"><Link href="/assistente-ia" aria-current="page">Monitoramento</Link><Link href="/ia">Configuração</Link></nav>
    <div className="mb-3"><FiltrosEquipe apoio={apoio} canais={canais} atualizado={formatarHora(new Date(),fuso)}/></div>
    <div className="grid gap-3 sm:grid-cols-3">{cards.map(c=><Link key={c.aba} href={link({aba:c.aba,pagina:'',conversa:''})} aria-current={aba===c.aba?'page':undefined} className={'metrica '+(aba===c.aba?'!border-produto-500':'')}><span className={'metrica-icone '+c.cor}><c.Icone size={24}/></span><div><p className="text-xs text-bruma-600">{c.nome}</p><p className="text-2xl font-semibold">{contagens[c.chave]||0}</p></div></Link>)}</div>
    {!!contagens.apoio&&<p className="aviso-operacional my-3"><TriangleAlert size={18}/>{contagens.apoio} atendimentos precisam de uma pessoa<Link className="ml-auto underline" href={link({aba:'apoio',pagina:'',conversa:''})}>Ver pedidos</Link></p>}
    <div className="mt-3 grid items-start gap-3 xl:grid-cols-[minmax(230px,.85fr)_minmax(320px,1.2fr)_minmax(260px,.9fr)]">
      <section className="superficie !p-0"><h2 className="titulo-painel border-b px-4 py-3 !mb-0">Fila de atendimentos</h2><p className="border-b bg-bruma-50 px-4 py-2 text-xs font-semibold">{cards.find(c=>c.aba===aba)?.nome} ({total})</p><ul className="divide-y">{itens.map(i=><li key={i.id}><Link href={link({conversa:i.id})} className={'flex gap-2 p-3 '+(escolhido?.id===i.id?'bg-produto-50':'')}><span className="min-w-0 flex-1"><Identidade nome={i.contato_nome} foto={i.contato_foto} pequeno/><span className="mt-2 block text-[11px] text-bruma-600">{i.falha_ia?'Não foi possível responder':i.estado==='AGUARDANDO_HUMANO'?'Precisa de um humano':'IA em atendimento'}</span></span>{i.espera_desde&&<span className="text-[11px] text-marca-600">{formatarEspera(i.espera_desde)}</span>}</Link></li>)}</ul>{!itens.length&&<p className="p-6 text-center text-sm text-bruma-600">Nenhum atendimento neste filtro.</p>}<div className="flex justify-between p-3 text-xs">{pagina>1&&<Link href={link({pagina:String(pagina-1)})}>← Anterior</Link>}{pagina*40<total&&<Link href={link({pagina:String(pagina+1)})}>Próxima →</Link>}</div></section>
      <section className="superficie"><h2 className="titulo-painel">Conversa em análise</h2>{escolhido&&detalhe?<><Identidade nome={escolhido.contato_nome} telefone={escolhido.canal_nome} foto={escolhido.contato_foto}/><p className="my-4 flex gap-2 rounded bg-ia-50 p-2 text-xs text-ia-700"><Sparkles size={16}/>{escolhido.com_ia?'Assistente IA em atendimento':'Aguardando humano · IA pausada'}</p><div className="min-h-40 space-y-4">{detalhe.mensagens.filter(m=>m.tipo!=='SISTEMA').slice(-6).map(m=><div key={m.id} className={m.autor==='IA'?'ml-5 rounded bg-ia-50 p-3 text-ia-700':'mr-5 rounded bg-bruma-100 p-3'}><p className="mb-1 text-[10px] text-bruma-600">{m.autor==='CONTATO'?escolhido.contato_nome:m.remetente_nome||'Assistente IA'} · {formatarHora(m.criado_em,fuso)}</p><p className="whitespace-pre-wrap text-xs leading-relaxed">{m.conteudo||'Mensagem de mídia'}</p></div>)}</div><Link className="mt-5 block text-center text-xs text-produto-800" href={'/atendimento?conversa='+escolhido.id}>Ver conversa completa →</Link><p className="mt-5 flex gap-2 border-t pt-3 text-[11px] text-bruma-600"><Info size={16}/>Uma mensagem automática não encerra a espera por um humano.</p></>:<p className="py-8 text-sm text-bruma-600">Selecione um atendimento para ver o contexto.</p>}</section>
      <aside className="superficie"><h2 className="titulo-painel">Passagem para humano</h2>{escolhido&&detalhe?<><dl className="mb-4 space-y-2 text-xs"><div className="flex justify-between gap-2"><dt className="text-bruma-600">Equipe</dt><dd>{escolhido.equipe_nome||'Sem equipe'}</dd></div><div className="flex justify-between gap-2"><dt className="text-bruma-600">Responsável</dt><dd>{escolhido.responsavel_nome||'Sem responsável'}</dd></div></dl><Intervencao key={escolhido.id} item={escolhido} apoio={apoio}/><h3 className="mb-2 mt-5 border-t pt-4 text-sm font-semibold">Contexto para o consultor</h3>{detalhe.contato.resumo?<><p className="mb-2 flex gap-1 text-[11px] text-ia-700"><Sparkles size={13}/>Resumo sugerido pela IA · revisar</p><p className="rounded bg-bruma-50 p-3 text-xs leading-relaxed">{detalhe.contato.resumo}</p></>:<p className="text-xs text-bruma-600">Ainda não há resumo disponível. Consulte as mensagens.</p>}<p className="mt-5 flex gap-2 text-[11px] text-bruma-600"><Info size={16}/>A IA só retoma após uma ação explícita.</p></>:<p className="py-8 text-sm text-bruma-600">Nenhuma ação necessária neste filtro.</p>}</aside>
    </div><SincronizadorLista organizacaoId={organizacaoId}/>
  </div>;
}
