'use client';
import Link from 'next/link';
import { UserRound,UsersRound,MessageSquare,Tag,Sparkles,ArrowRight } from 'lucide-react';
import { Identidade,Situacao } from '@/componentes/operacao/compartilhados';
import { AgendarRetorno } from '@/componentes/operacao/agendar-retorno';
import { formatarTelefone } from '@/lib/nucleo/telefone';
import { formatarDataHora } from '@/lib/utilitarios';
import type { DetalheConversa,ApoioAtendimento } from './tipos';
import type { FilaOperacional } from '@/lib/operacao/tipos';
import { FichaContato } from './ficha';
export function ContextoContato({detalhe,apoio,operacional,membroId,fuso}:{detalhe:DetalheConversa;apoio:ApoioAtendimento;operacional:FilaOperacional|null;membroId:string;fuso:string}){
 const {contato,conversa}=detalhe;const nome=contato.nome||contato.nome_perfil_whatsapp||contato.telefone;
 return <div className="p-4 text-xs"><h2 className="titulo-painel">Contato</h2><Link href={'/contatos/'+contato.id}><Identidade nome={nome} telefone={formatarTelefone(contato.telefone)} foto={contato.foto_url}/></Link><section className="mt-5 border-t pt-4"><h3 className="titulo-painel !text-[13px]">Atendimento</h3><dl className="space-y-3"><div className="flex items-center gap-2"><UsersRound size={14}/><dt className="text-bruma-600">Equipe</dt><dd className="ml-auto">{detalhe.departamento?.nome||'Sem equipe'}</dd></div><div className="flex items-center gap-2"><UserRound size={14}/><dt className="text-bruma-600">Responsável</dt><dd className="ml-auto">{detalhe.responsavelNome||'Sem responsável'}</dd></div><div className="flex items-center gap-2"><MessageSquare size={14}/><dt className="text-bruma-600">Canal</dt><dd className="ml-auto">{detalhe.canal?.nome||'Não informado'}</dd></div></dl></section><section className="mt-5 border-t pt-4"><h3 className="titulo-painel !text-[13px]">Etiquetas</h3><div className="flex flex-wrap items-center gap-1.5"><Tag size={14}/>{apoio.etiquetas.filter(e=>detalhe.etiquetasDaConversa.includes(e.id)||detalhe.etiquetasDoContato.includes(e.id)).map(e=><span className="rounded-full bg-produto-50 px-2 py-1 text-[11px] text-produto-800" key={e.id}>{e.nome}</span>)}{!detalhe.etiquetasDaConversa.length&&!detalhe.etiquetasDoContato.length&&<span className="text-bruma-600">Sem etiquetas</span>}</div></section><section className="mt-5 border-t pt-4"><h3 className="titulo-painel !text-[13px]">Próxima ação</h3>{operacional&&<div className="mb-3"><Situacao item={operacional}/></div>}{operacional?.retorno_prazo&&<Link className="mb-3 block text-produto-800" href={'/retornos?conversa='+conversa.id}>{operacional.retorno_motivo} · {formatarDataHora(operacional.retorno_prazo,fuso)}</Link>}{conversa.estado!=='ENCERRADA'&&<AgendarRetorno conversaId={conversa.id} nome={nome} membroId={membroId} fuso={fuso}/>}</section>{contato.resumo&&<section className="mt-5 border-t pt-4"><h3 className="titulo-painel !text-[13px]">Resumo da conversa</h3><div className="rounded border bg-bruma-50 p-3 leading-relaxed">{contato.resumo}<span className="mt-2 flex items-center gap-1 text-[10px] text-ia-700"><Sparkles size={12}/>Sugestão da IA · revisar</span><span className="text-[10px] text-bruma-600">{formatarDataHora(contato.resumo_atualizado_em,fuso)}</span></div></section>}<Link className="mt-5 flex items-center justify-between text-produto-800" href={'/contatos/'+contato.id}>Ver perfil completo<ArrowRight size={14}/></Link><details className="mt-5 border-t pt-3"><summary className="cursor-pointer text-bruma-600">Campos, etiquetas e memória</summary><FichaContato detalhe={detalhe} apoio={apoio} embutida/></details></div>;
}
