'use client';
import Link from 'next/link';
import { useRouter,useSearchParams } from 'next/navigation';
import { Search,ArrowDownWideNarrow,ChevronLeft,ChevronRight } from 'lucide-react';
import { CAIXAS_OPERACIONAIS,type FilaOperacional } from '@/lib/operacao/tipos';
import { iniciais,tempoRelativo } from '@/lib/utilitarios';
import { Situacao } from '@/componentes/operacao/compartilhados';
import type { ApoioAtendimento } from './tipos';
export function ListaOperacional({itens,contagens,total,pagina,apoio,propria}:{itens:FilaOperacional[];contagens:Record<string,number>;total:number;pagina:number;apoio:ApoioAtendimento;propria:boolean}){
 const q=useSearchParams(),router=useRouter();const caixa=q.get('caixa')||'prioridades';
 function url(m:Record<string,string>){const p=new URLSearchParams(q.toString());for(const [k,v]of Object.entries(m)){if(v)p.set(k,v);else p.delete(k);}return '/atendimento?'+p.toString();}
 return <>
  <div className="px-3 pt-3"><div className="mb-3 flex items-center justify-between gap-2"><h1 className="text-lg font-semibold">{propria?'Minha fila':'Fila da equipe'} <span className="ml-1 rounded bg-bruma-100 px-1.5 text-xs">{contagens.todos||0}</span></h1><select aria-label="Escopo da fila" value={propria?'minha':'equipe'} onChange={e=>router.push(url({escopo:e.target.value,pagina:''}))} className="max-w-[102px] rounded border p-1 text-[11px]"><option value="minha">Minha fila</option><option value="equipe">Da equipe</option></select></div>
  <form onSubmit={e=>{e.preventDefault();router.push(url({busca:String(new FormData(e.currentTarget).get('busca')||''),pagina:''}));}} className="relative"><Search size={14} className="absolute left-2.5 top-2.5 text-bruma-600"/><input aria-label="Buscar nome ou telefone" name="busca" type="search" defaultValue={q.get('busca')||''} key={q.get('busca')||''} placeholder="Buscar nome ou telefone" className="campo-operacional !h-8 !pl-8"/><button type="submit" className="sr-only">Buscar</button></form>
  <nav className="my-3 grid grid-cols-3 gap-1.5" aria-label="Filtros da fila">{CAIXAS_OPERACIONAIS.map(c=><Link key={c.id} href={url({caixa:c.id,pagina:''})} scroll={false} className="filtro-fila" aria-current={caixa===c.id?'true':undefined}>{c.rotulo}<span className="rounded bg-black/5 px-1 text-[10px]">{contagens[c.id]||0}</span></Link>)}</nav>
  <div className="flex items-center gap-1 rounded border px-2"><ArrowDownWideNarrow size={14}/><select aria-label="Ordenação" className="h-8 min-w-0 flex-1 bg-white text-xs" value={q.get('ordem')||'urgencia'} onChange={e=>router.push(url({ordem:e.target.value,pagina:''}))}><option value="urgencia">Mais urgentes primeiro</option><option value="recentes">Atividade mais recente</option></select></div>
  <details className="my-2 text-[11px] text-bruma-600"><summary className="cursor-pointer py-1">Equipe e outras filas</summary><select aria-label="Filtrar equipe" className="campo-operacional my-2" value={q.get('equipe')||''} onChange={e=>router.push(url({equipe:e.target.value,pagina:''}))}><option value="">Todas as equipes</option>{apoio.departamentos.map(d=><option key={d.id} value={d.id}>{d.nome}</option>)}</select><div className="flex flex-wrap gap-2">{([['ia','Com IA'],['sem-responsavel','Sem responsável'],['encerradas','Concluídas']] as const).map(([id,n])=><Link key={id} className="underline" href={url({caixa:id,escopo:'equipe',pagina:''})}>{n}</Link>)}</div></details>
  <p className="mb-2 text-[11px] text-bruma-600">{caixa==='prioridades'?'Clientes aguardando e retornos vencidos':total+' conversas neste filtro'}</p></div>
  <div className="min-h-0 flex-1 overflow-y-auto rolagem-fina"><ul>{itens.map(i=><li key={i.id}><Link href={url({conversa:i.id})} scroll={false} className="item-conversa" aria-current={q.get('conversa')===i.id?'true':undefined}><span className="avatar">{iniciais(i.contato_nome)}</span><span className="min-w-0 flex-1"><span className="flex items-center justify-between gap-1"><span className="truncate text-[12px] font-semibold">{i.contato_nome}</span><Situacao item={i}/></span><span className="my-1 block truncate text-[12px] text-tinta-700">{i.ultimo_texto||'Nenhuma mensagem pública'}</span><span className="flex items-center justify-between text-[10px] text-bruma-600"><span>{i.ultimo_autor==='CONTATO'?'Cliente':i.ultimo_autor==='IA'?'IA':i.responsavel_nome||'Equipe'} · {tempoRelativo(i.ultimo_publico_em)}</span>{i.nao_lidas>0&&<span className="rounded-full bg-produto-700 px-1.5 py-0.5 text-white">{i.nao_lidas}</span>}</span></span></Link></li>)}</ul>{!itens.length&&<p className="p-6 text-center text-sm text-bruma-600">Nenhuma conversa neste filtro. Confira a fila da equipe ou escolha Todos.</p>}</div>
  <div className="flex items-center justify-between border-t p-2 text-[11px] text-bruma-600"><span>{total?((pagina-1)*40+1)+'–'+Math.min(pagina*40,total):0} de {total}</span><div className="flex gap-1">{pagina>1&&<Link aria-label="Página anterior" href={url({pagina:String(pagina-1)})} className="rounded border p-1"><ChevronLeft size={16}/></Link>}{pagina*40<total&&<Link aria-label="Próxima página" href={url({pagina:String(pagina+1)})} className="rounded border p-1"><ChevronRight size={16}/></Link>}</div></div>
 </>;
}
